services:
  resume_panel:
    container_name: resume_panel_nuxt
    build: .
    command: ["npm", "run", "start"]
    volumes:
      - .:/app
    ports:
      - "3001:3000"
    expose:
      - "3000"
    networks:
      - local_network

networks:
  local_network:
    external: true