services:
  resume_panel:
    container_name: resume_panel_nuxt
    build: .
    command: ["npm", "run", "start"]
    volumes:
      - .:/app
    ports:
      - "3000:3001"
    expose:
      - "3001"

networks:
  local_network:
    external: true